// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Location struct {
	ID int64 `json:"id"`
	// name of city
	Name      string  `json:"name"`
	Longitude float64 `json:"longitude"`
	Latitude  float64 `json:"latitude"`
	// to count visited
	Count int32 `json:"count"`
}
